name = "gwurr3tech"
license = "ISC"
licenselink = "https://raw.githubusercontent.com/gwurr3/gwurr3tech/master/LICENSE"
description = "gwurr3's basic tech blog theme"
homepage = "http://gwurr3.me/"
tags = [
	"minimalist",
	"technical",
	"accessible",
	"simple"
]
features = [
	"baddass",
	"changeme"
]
min_version = "0.27.1"

[author]
	name = "gwurr3"
	homepage = "http://gwurr3.me/"

